# fly.toml app configuration file generated for xtdb on 2026-02-02T20:10:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xtdb'
primary_region = 'fra'

[build]
  image = 'ghcr.io/xtdb/xtdb:latest'

[env]
  JAVA_TOOL_OPTIONS = '-XX:MaxRAMPercentage=80.0'

[[mounts]]
  source = 'xtdb_data'
  destination = '/var/lib/xtdb'
  initial_size = '2GB'
  snapshot_retention = 14
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '50GB'

[[services]]
  internal_port = 5432
  protocol = 'tcp'
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 5432

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
  cpus = 2
  memory_mb = 2048
